# Generated by Django 5.0.6 on 2024-07-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creacionUsuario',
        ),
    ]
